version: '3.3'
services:
  web:
    image: maxiplux/livemarket.business.b2bcart:1.0.2
    volumes:
      - ./composeexample:/code
    environment:
      POSTGRESQL_ADDRESS: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRESQL_DATABASE : postgres
      POSTGRESQL_USERNAME: postgres
      DATABASE_PORT : 5432
    ports:
      - "8080:8080"
    links:
      - postgres
    depends_on:
      - postgres
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

volumes:
  dbdata:
# this compomse no has it https://thepracticaldeveloper.com/2017/12/11/dockerize-spring-boot/ , but  that exmaple is beautiful because implements scale
